all:
	R --no-save < results/boxplot_CMA_ES_F0.R
	R --no-save < results/boxplot_CMA_ES_F1.R
	R --no-save < results/boxplot_CMA_ES_F2.R
	R --no-save < results/boxplot_CMA_ES_F3.R
	R --no-save < results/boxplot_CMA_ES_F4.R
	R --no-save < results/boxplot_CMA_ES_F5.R
	R --no-save < results/boxplot_CMA_ES_F6.R
	R --no-save < results/boxplot_CMA_ES_F7.R
	R --no-save < results/boxplot_CMA_ES_F8.R
	R --no-save < results/boxplot_CMA_ES_F9.R
	R --no-save < results/boxplot_CMA_ES_F10.R
	R --no-save < results/boxplot_CMA_ES_F11.R
	R --no-save < results/boxplot_CMA_ES_F12.R
	R --no-save < results/boxplot_CMA_ES_F13.R
	R --no-save < results/boxplot_CMA_ES_F14.R
	R --no-save < results/boxplot_CMA_ES_F15.R
	R --no-save < results/boxplot_CMA_ES_F16.R
	R --no-save < results/boxplot_CMA_ES_F17.R
	gnuplot results/mean_error_evolution_CMA_ES_F0.plot
	gnuplot results/mean_error_evolution_CMA_ES_F1.plot
	gnuplot results/mean_error_evolution_CMA_ES_F2.plot
	gnuplot results/mean_error_evolution_CMA_ES_F3.plot
	gnuplot results/mean_error_evolution_CMA_ES_F4.plot
	gnuplot results/mean_error_evolution_CMA_ES_F5.plot
	gnuplot results/mean_error_evolution_CMA_ES_F6.plot
	gnuplot results/mean_error_evolution_CMA_ES_F7.plot
	gnuplot results/mean_error_evolution_CMA_ES_F8.plot
	gnuplot results/mean_error_evolution_CMA_ES_F9.plot
	gnuplot results/mean_error_evolution_CMA_ES_F10.plot
	gnuplot results/mean_error_evolution_CMA_ES_F11.plot
	gnuplot results/mean_error_evolution_CMA_ES_F12.plot
	gnuplot results/mean_error_evolution_CMA_ES_F13.plot
	gnuplot results/mean_error_evolution_CMA_ES_F14.plot
	gnuplot results/mean_error_evolution_CMA_ES_F15.plot
	gnuplot results/mean_error_evolution_CMA_ES_F16.plot
	gnuplot results/mean_error_evolution_CMA_ES_F17.plot		

clean:
	rm -f *.log *.dvi *.aux *.bbl *.blg *~
	
cleanall:
	rm -f *.log *.dvi *.aux *.bbl *.blg *~ *.backup *.ps *.out *.spl *.eps
